"""API regression tests for PolicyFlow graph validation / export / run flows.

Run: cd backend && python -m pytest tests/ -v
"""

import json


class TestHealthAndCatalog:
    """Health and catalog endpoints for workspace bootstrapping."""

    def test_health_endpoint(self, client) -> None:
        resp = client.get("/api/health")
        assert resp.status_code == 200
        body = resp.json()
        assert body["status"] == "ok"
        assert body["service"] == "policyflow-backend"

    def test_node_catalog_has_four_groups(self, client) -> None:
        resp = client.get("/api/node-catalog")
        assert resp.status_code == 200
        body = resp.json()
        assert isinstance(body["groups"], list)
        assert len(body["groups"]) >= 4
        assert any(g["key"] == "training" for g in body["groups"])

    def test_node_catalog_singleton_returns_same_data(self, client) -> None:
        """Verify the Singleton NodeRegistry returns identical data on repeated calls."""
        r1 = client.get("/api/node-catalog").json()
        r2 = client.get("/api/node-catalog").json()
        assert r1 == r2


class TestGraphValidation:
    """DAG validation and execution order checks."""

    def test_validate_returns_execution_order(self, client, sample_graph) -> None:
        resp = client.post("/api/graphs/validate", json=sample_graph)
        assert resp.status_code == 200
        body = resp.json()
        order = body["execution_order"]
        assert len(order) == len(sample_graph["nodes"])
        assert order[0]["id"] == "node-dataset-1"
        assert order[-1]["id"] == "node-ppo-1"

    def test_validate_rejects_cycle(self, client, sample_graph) -> None:
        payload = json.loads(json.dumps(sample_graph))
        payload["edges"].append({
            "id": "edge-cycle-1",
            "source": "node-ppo-1",
            "target": "node-dataset-1",
        })
        resp = client.post("/api/graphs/validate", json=payload)
        assert resp.status_code == 400
        detail = resp.json()["detail"].lower()
        assert "cycle" in detail or "dag" in detail

    def test_validate_rejects_missing_node_edge(self, client) -> None:
        payload = {
            "nodes": [{"id": "a", "type": "dataset", "position": {}, "data": {}}],
            "edges": [{"id": "e1", "source": "a", "target": "nonexistent"}],
        }
        resp = client.post("/api/graphs/validate", json=payload)
        assert resp.status_code == 400


class TestCodeExport:
    """Readable Python export checks."""

    def test_export_returns_script_and_config(self, client, sample_graph) -> None:
        resp = client.post("/api/export", json=sample_graph)
        assert resp.status_code == 200
        body = resp.json()
        assert "script" in body and "config" in body
        assert "def main()" in body["script"]
        assert "graph_config" in body["script"]
        assert body["config"]["node_count"] == len(sample_graph["nodes"])

    def test_export_script_contains_auto_generated_header(self, client, sample_graph) -> None:
        body = client.post("/api/export", json=sample_graph).json()
        assert "Auto-generated by PolicyFlow" in body["script"]


class TestRunExecution:
    """Run trigger checks with execution mode contract."""

    def test_run_returns_dry_run_mode(self, client, sample_graph) -> None:
        resp = client.post("/api/run", json=sample_graph)
        assert resp.status_code == 200
        body = resp.json()
        assert body["mode"] == "validation-dry-run"
        assert len(body["execution_order"]) == len(sample_graph["nodes"])

    def test_run_returns_lightweight_mode_for_classical(self, client, sample_graph) -> None:
        payload = json.loads(json.dumps(sample_graph))
        payload["nodes"].append({
            "id": "node-classical-2",
            "type": "classical",
            "position": {"x": 510, "y": 300},
            "data": {
                "label": "Classical ML Block",
                "subtitle": "Tabular baseline",
                "badge": "ml",
                "params": {
                    "algorithm": "random_forest",
                    "library": "scikit-learn",
                    "objective": "classification",
                    "metric": "accuracy",
                },
            },
        })
        payload["edges"].append({
            "id": "edge-classical-1",
            "source": "node-dataset-1",
            "target": "node-classical-2",
        })
        resp = client.post("/api/run", json=payload)
        assert resp.status_code == 200
        body = resp.json()
        assert body["mode"] == "lightweight-local"
        assert any(s["id"] == "node-classical-2" for s in body["execution_order"])

    def test_run_response_includes_script(self, client, sample_graph) -> None:
        body = client.post("/api/run", json=sample_graph).json()
        assert "Auto-generated by PolicyFlow" in body["script"]
