"""07_code_generator.py — Factory Pattern: Generates executable Python from a visual graph.

Why: Each node type requires a distinct code-generation strategy. The Factory
pattern dispatches to the correct renderer per node type, keeping the
generator open for extension without modification (OCP).
"""

import json
from textwrap import dedent

from src import load_module

_m03 = load_module("03_graph_payload")
GraphPayload = _m03.GraphPayload


class CodeGenerator:
    """Factory: Dispatches code rendering per node type to produce a runnable Python script."""

    # --- Factory dispatch table ---
    _RENDERERS: dict[str, str] = {
        "dataset": "_render_dataset",
        "model": "_render_model",
        "training": "_render_training",
        "classical": "_render_classical",
        "output": "_render_output",
    }

    def generate(self, payload: GraphPayload, execution_order: list[dict]) -> dict:
        config = self._build_config(payload, execution_order)
        script = self._render_script(payload, config)
        return {"config": config, "script": script}

    def _build_config(self, payload: GraphPayload, execution_order: list[dict]) -> dict:
        node_map = {node.id: node for node in payload.nodes}
        ordered_nodes = []
        for item in execution_order:
            node = node_map[item["id"]]
            ordered_nodes.append(
                {
                    "id": node.id,
                    "type": node.type,
                    "label": node.data.get("label", node.id),
                    "params": node.data.get("params", {}),
                    "upstream": item["upstream"],
                }
            )
        return {
            "project": "PolicyFlow",
            "node_count": len(payload.nodes),
            "edge_count": len(payload.edges),
            "execution_order": ordered_nodes,
        }

    def _render_script(self, payload: GraphPayload, config: dict) -> str:
        ordered_nodes = config["execution_order"]
        types = {n["type"] for n in ordered_nodes}
        strategies = {n["params"].get("strategy") for n in ordered_nodes if n["type"] == "training"}

        import_lines = self._collect_imports(types, strategies)
        node_lines: list[str] = []

        for node in ordered_nodes:
            renderer_name = self._RENDERERS.get(node["type"])
            if renderer_name:
                renderer = getattr(self, renderer_name)
                node_lines.extend(renderer(node))

        config_json = json.dumps(config, indent=2)
        imports = "\n".join(dict.fromkeys(import_lines))
        body = "\n".join(node_lines)

        return dedent(f"""
            # Auto-generated by PolicyFlow
            # This script mirrors the current DAG and keeps node configs readable.

            {imports}

            graph_config = {config_json}
            graph_nodes = {{node['id']: node for node in graph_config['execution_order']}}


            def main() -> None:
                Path('artifacts').mkdir(exist_ok=True)
                print('Execution order:', [node['label'] for node in graph_config['execution_order']])
            {body}


            if __name__ == '__main__':
                main()
        """).strip()

    # --- Import collection ---

    @staticmethod
    def _collect_imports(types: set[str], strategies: set[str]) -> list[str]:
        lines = ["from pathlib import Path", "import json"]

        if "dataset" in types:
            lines.extend(["# Optional: pip install datasets pandas", "from datasets import load_dataset"])

        if {"model", "training"} & types:
            lines.extend([
                "# Optional: pip install transformers accelerate",
                "from transformers import AutoModelForCausalLM, AutoTokenizer",
            ])

        if any(s in {"lora", "qlora"} for s in strategies):
            lines.extend(["# Optional: pip install peft", "from peft import LoraConfig, get_peft_model"])

        if any(s in {"sft", "ppo", "rlhf", "dpo"} for s in strategies):
            lines.extend([
                "# Optional: pip install trl",
                "from trl import DPOConfig, DPOTrainer, PPOConfig, PPOTrainer, SFTConfig, SFTTrainer",
            ])

        if "classical" in types:
            lines.extend([
                "from sklearn.metrics import accuracy_score, f1_score",
                "from sklearn.model_selection import train_test_split",
                "from sklearn.ensemble import RandomForestClassifier",
                "from sklearn.svm import SVC",
            ])

        return lines

    # --- Per-node renderers (Factory products) ---

    def _render_dataset(self, node: dict) -> list[str]:
        var = self._safe_name(node["id"])
        params = node["params"]
        lines = [f"\n    # --- {node['label']} ({node['type']}) ---"]

        if params.get("sourceType") == "huggingface":
            lines.extend([
                f"    {var}_cfg = graph_nodes['{node['id']}']",
                f"    {var} = load_dataset({var}_cfg['params']['datasetName'], split={var}_cfg['params']['split'])",
            ])
        else:
            lines.extend([
                f"    {var}_cfg = graph_nodes['{node['id']}']",
                f"    {var}_path = Path({var}_cfg['params']['datasetName'])",
                "    # Replace with pandas.read_csv / read_json / parquet loader as needed",
                f"    {var} = {{'path': str({var}_path), 'format': {var}_cfg['params']['format']}}",
            ])
        return lines

    def _render_model(self, node: dict) -> list[str]:
        var = self._safe_name(node["id"])
        return [
            f"\n    # --- {node['label']} ({node['type']}) ---",
            f"    {var}_cfg = graph_nodes['{node['id']}']",
            f"    {var}_tokenizer = AutoTokenizer.from_pretrained({var}_cfg['params']['modelId'])",
            f"    {var}_model = AutoModelForCausalLM.from_pretrained({var}_cfg['params']['modelId'])",
        ]

    def _render_training(self, node: dict) -> list[str]:
        var = self._safe_name(node["id"])
        strategy = node["params"].get("strategy")
        lines = [f"\n    # --- {node['label']} ({node['type']}) ---"]

        if strategy in {"lora", "qlora"}:
            lines.extend([
                f"    {var}_cfg = graph_nodes['{node['id']}']",
                f"    {var}_adapter = LoraConfig(r=16, lora_alpha=32, target_modules=['q_proj', 'v_proj'])",
                "    base_model_node = next(item for item in graph_config['execution_order'] if item['type'] == 'model')",
                "    base_model_key = base_model_node['id'].replace('-', '_')",
                f"    {var}_model = get_peft_model(locals()[base_model_key + '_model'], {var}_adapter)",
            ])
        elif strategy == "sft":
            lines.extend([
                f"    {var}_cfg = graph_nodes['{node['id']}']",
                f"    {var}_args = SFTConfig(output_dir='artifacts/sft', learning_rate=float({var}_cfg['params']['learningRate']), num_train_epochs=int({var}_cfg['params']['epochs']))",
                "    dataset_node = next(item for item in graph_config['execution_order'] if item['type'] == 'dataset')",
                "    model_node = next(item for item in graph_config['execution_order'] if item['type'] == 'model')",
                "    dataset_key = dataset_node['id'].replace('-', '_')",
                "    model_key = model_node['id'].replace('-', '_')",
                f"    {var}_trainer = SFTTrainer(model=locals()[model_key + '_model'], tokenizer=locals()[model_key + '_tokenizer'], train_dataset=locals()[dataset_key], args={var}_args)",
                f"    {var}_trainer.train()",
            ])
        elif strategy in {"ppo", "rlhf"}:
            lines.extend([
                f"    {var}_cfg = graph_nodes['{node['id']}']",
                f"    {var}_args = PPOConfig(learning_rate=float({var}_cfg['params']['learningRate']), batch_size=4, mini_batch_size=2)",
                "    dataset_node = next(item for item in graph_config['execution_order'] if item['type'] == 'dataset')",
                "    model_node = next(item for item in graph_config['execution_order'] if item['type'] == 'model')",
                "    dataset_key = dataset_node['id'].replace('-', '_')",
                "    model_key = model_node['id'].replace('-', '_')",
                f"    {var}_trainer = PPOTrainer(config={var}_args, model=locals()[model_key + '_model'], tokenizer=locals()[model_key + '_tokenizer'], dataset=locals()[dataset_key])",
                f"    print('PPO pipeline ready:', {var}_trainer)",
            ])
        elif strategy == "dpo":
            lines.extend([
                f"    {var}_cfg = graph_nodes['{node['id']}']",
                f"    {var}_args = DPOConfig(output_dir='artifacts/dpo', learning_rate=float({var}_cfg['params']['learningRate']), num_train_epochs=int({var}_cfg['params']['epochs']))",
                "    dataset_node = next(item for item in graph_config['execution_order'] if item['type'] == 'dataset')",
                "    model_node = next(item for item in graph_config['execution_order'] if item['type'] == 'model')",
                "    dataset_key = dataset_node['id'].replace('-', '_')",
                "    model_key = model_node['id'].replace('-', '_')",
                f"    {var}_trainer = DPOTrainer(model=locals()[model_key + '_model'], args={var}_args, train_dataset=locals()[dataset_key], processing_class=locals()[model_key + '_tokenizer'])",
                f"    {var}_trainer.train()",
            ])
        return lines

    def _render_classical(self, node: dict) -> list[str]:
        var = self._safe_name(node["id"])
        algorithm = node["params"].get("algorithm")
        lines = [
            f"\n    # --- {node['label']} ({node['type']}) ---",
            f"    {var}_cfg = graph_nodes['{node['id']}']",
            "    from sklearn.datasets import load_breast_cancer",
            "    demo = load_breast_cancer(as_frame=True)",
            "    X_train, X_test, y_train, y_test = train_test_split(demo.data, demo.target, test_size=0.2, random_state=42)",
        ]

        if algorithm == "svm":
            lines.append(f"    {var}_model = SVC(kernel='rbf', probability=True)")
        elif algorithm == "random_forest":
            lines.append(f"    {var}_model = RandomForestClassifier(n_estimators=200, random_state=42)")
        else:
            lines.extend([
                "    try:",
                "        from xgboost import XGBClassifier",
                f"        {var}_model = XGBClassifier(max_depth=4, n_estimators=200, learning_rate=0.1, subsample=0.9)",
                "    except Exception:",
                f"        {var}_model = RandomForestClassifier(n_estimators=200, random_state=42)",
            ])

        lines.extend([
            f"    {var}_model.fit(X_train, y_train)",
            f"    {var}_preds = {var}_model.predict(X_test)",
            f"    print('accuracy', accuracy_score(y_test, {var}_preds))",
            f"    print('f1', f1_score(y_test, {var}_preds))",
        ])
        return lines

    def _render_output(self, node: dict) -> list[str]:
        var = self._safe_name(node["id"])
        return [
            f"\n    # --- {node['label']} ({node['type']}) ---",
            f"    {var}_cfg = graph_nodes['{node['id']}']",
            f"    print('Output node ready ->', {var}_cfg['params'])",
        ]

    @staticmethod
    def _safe_name(value: str) -> str:
        return value.replace("-", "_")
